/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DynamicForm: typeof import('./src/components/DynamicForm/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElText: typeof import('element-plus/es')['ElText']
    GlobalIcon: typeof import('./src/components/GlobalIcon/index.vue')['default']
    Index: typeof import('./src/components/MobileDrawer/Index.vue')['default']
    MediaTable: typeof import('./src/components/MediaTable/index.vue')['default']
    MediaViewer: typeof import('./src/components/MediaViewer/index.vue')['default']
    MeowCard: typeof import('./src/components/MeowCard/index.vue')['default']
    MeowDialog: typeof import('./src/components/MeowDialog/index.vue')['default']
    MeowDrawer: typeof import('./src/components/MeowDrawer/index.vue')['default']
    MeowSelect: typeof import('./src/components/MeowSelect/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowDetails: typeof import('./src/components/ShowDetails/index.vue')['default']
    SvgIcons: typeof import('./src/components/SvgIcons/index.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar/index.vue')['default']
    TypewriterEffect: typeof import('./src/components/TypewriterEffect/index.vue')['default']
    WaterfallFlow: typeof import('./src/components/WaterfallFlow/index.vue')['default']
  }
}
