/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DynamicForm: typeof import('./src/components/DynamicForm/index.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    GlobalIcon: typeof import('./src/components/GlobalIcon/index.vue')['default']
    Index: typeof import('./src/components/MobileDrawer/Index.vue')['default']
    MediaTable: typeof import('./src/components/MediaTable/index.vue')['default']
    MediaViewer: typeof import('./src/components/MediaViewer/index.vue')['default']
    MeowCard: typeof import('./src/components/MeowCard/index.vue')['default']
    MeowDialog: typeof import('./src/components/MeowDialog/index.vue')['default']
    MeowDrawer: typeof import('./src/components/MeowDrawer/index.vue')['default']
    MeowSelect: typeof import('./src/components/MeowSelect/index.vue')['default']
    ProgressiveImage: typeof import('./src/components/ProgressiveImage/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowDetails: typeof import('./src/components/ShowDetails/index.vue')['default']
    SvgIcons: typeof import('./src/components/SvgIcons/index.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar/index.vue')['default']
    TypewriterEffect: typeof import('./src/components/TypewriterEffect/index.vue')['default']
    WaterfallFlow: typeof import('./src/components/WaterfallFlow/index.vue')['default']
  }
}
